plugins {
    id 'java'
}

def rootProps = new Properties()
rootProps.load(new FileInputStream(file('../gradle.properties')))

group = 'io.github.sfkamath'
version = findProperty('pluginVersion') ?: rootProps['pluginVersion']

repositories {
    mavenCentral()
}

dependencies {
    compileOnly "org.projectlombok:lombok:${rootProps['lombokVersion']}"
    annotationProcessor "org.projectlombok:lombok:${rootProps['lombokVersion']}"

    testCompileOnly "org.projectlombok:lombok:${rootProps['lombokVersion']}"
    testAnnotationProcessor "org.projectlombok:lombok:${rootProps['lombokVersion']}"

    implementation "com.fasterxml.jackson.core:jackson-databind:${rootProps['jacksonVersion']}"

    testImplementation "org.junit.jupiter:junit-jupiter-api:${rootProps['junitVersion']}"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:${rootProps['junitVersion']}"
    testImplementation "org.junit.jupiter:junit-jupiter-params:${rootProps['junitVersion']}"
    testImplementation "org.assertj:assertj-core:${rootProps['assertjVersion']}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:${rootProps['junitPlatformVersion']}"
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

test {
    useJUnitPlatform()
}
